### ISSUE TITLE
UNITTEST の書き方

### ISSUE THREAD

**Issue by kzrnm** [competitive-verifier/competitive-verifier#17]
[online-judge-tools/verification-helper](https://github.com/online-judge-tools/verification-helper) は [Hello World](http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=ITP1_1_A) をダミーとしてユニットテストを書くように言っている。
https://github.com/online-judge-tools/verification-helper/issues/233

これだと C# や Go のように `main()` で実行するわけではないユニットテストでは使えない。

----

こういう使い方ができることを書く。

```go
// competitive-verifier: UNITTEST GOTESTRESULT

package main

import (
    "testing"
    "./helloworld"
)

func TestHelloWorld(t *testing.T) {
    want:= "Hello World"
    if got := helloworld.GetHelloWorld(); got != want {
        t.Errorf("helloworld.GetHelloWorld() = %v, want %v", got, want)
    }
}
```

```yml
      - name: go test
        id: go-unittest
        run: go test
        working-directory: examples/go
        continue-on-error: true
        env:
          GO111MODULE: "off"

      - name: oj-resolve
        uses: competitive-verifier/actions/oj-resolve@v1
        with:
          include: examples
          exclude: |
            src
            tests
          output-path: resolved.json
          config: examples/awk-config.toml
        env:
          GOTESTRESULT: ${{ steps.go-unittest.outcome == 'success' }}
```
