### ISSUE TITLE
verify の --prev-result が効かない

### ISSUE THREAD

**Issue by kzrnm** [competitive-verifier/competitive-verifier#76]
`--prev-result` を使うときは `fetch-depth: 0` が必要であることを書く必要がある。

```yaml
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
```
